### ISSUE TITLE
Lavadynamics causing server crash while in void in the End (Void world generation errors)

### ISSUE THREAD

**Issue by Hirschney** [kreezxil/Lava-Dynamics#16]
Server crashes as people open chunks in the End - LavaDynamics appears to be trying to spawn a volcano and causing a server hang.

[crash report.txt](https://github.com/kreezxil/Lava-Dynamics/files/3326172/crash.report.txt)

**Comment by kreezxil** [comment]
with Stygian End installed too, he left that out.

**Comment by eleksploded** [comment]
I've pushed a build on curseforge (5.5.11) to fix crashing. It is a workaround and you shouldn't enable generation in the end (or any void world) for now. I'm going to leave the issue open until that is totally fixed.

**Comment by eleksploded** [comment]
Fixed in 5.6.8
