### ISSUE TITLE
WorldSmelting does not handle metadata

### ISSUE THREAD

**Issue by SirLyle** [kreezxil/Lava-Dynamics#17]
[Originally reported on the Ex Nihilo Creatio issue page](https://github.com/BloodyMods/ExNihiloCreatio/issues/242)

ENC has a furnace recipe which is

> unfired crucible -> fired crucible

Where the difference in the two blocks/items is their metadata. It appears that when a user attempts to place fired crucible over lava that LavaDynamics is identifying it as an unfired crucible, "smelting" it, and placing an unfired crucible in its place.

The root cause appears to be [this function](https://github.com/kreezxil/Lava-Dynamics/blob/5b4bee45fda72ed3d6c63d7379d0b30cd111bcf9/1.12.2/src/main/java/com/eleksploded/lavadynamics/WorldSmelting.java#L71) which does not check/save metadata.

**Comment by SirLyle** [comment]
To fix it you'll probably want to do something like this (untested) code

````java
    private static void CheckNSmelt(World world, BlockPos pos) {
        //Get Variables cause I'm a lazy programmer and don't want to type the things multiple times
        final IBlockState state = world.getBlockState(pos);
        final Block block = state.getBlock();

        ItemStack input = Item.getItemFromBlock(block).getHasSubtypes() ?
                new ItemStack(block, 1, block.getMetaFromState(state)) : new ItemStack(block);
        ItemStack result = FurnaceRecipes.instance().getSmeltingResult(input);
        //Check if Block has a smelting result that is a block
        if(!result.isEmpty() && result.getItem() instanceof ItemBlock) {
            final IBlockState newState = ((ItemBlock) result.getItem()).getBlock().getStateFromMeta(result.getMetadata());
            //Set Resulting Block in world
            if(!blacklist.contains(newState.getBlock().getRegistryName().toString()))
                world.setBlockState(pos,newState);
        }
    }
````

**Comment by eleksploded** [comment]
I will fix this when I get home today. Also, thanks for the code example!

**Comment by WenXin20** [comment]
The volcano ore config also doesn't appear to accept metadata, such as with `funores:metalores:1` or `actuallyadditions:block_misc:3`.
