### ISSUE TITLE
Crash w/ World Creation, WildNature World Type

### ISSUE THREAD

**Issue by WenXin20** [kreezxil/Lava-Dynamics#21]
## Describe the bug
I got this crash after creating a new world using the WildNature World Type.

## To Reproduce
1. Create a New World
2. Choose WildNature as the World Type
3. Crash

## Versions:
 - Lava Dynamics: v5.6.6
- [WildNature](https://www.curseforge.com/minecraft/mc-mods/wildnature): v1.2.0
 - Version of Forge you are using: v14.23.5.2838

## Logs (REQUIRED):
 - [Crash Report](https://gist.github.com/WenXin20/677c66e15048d9d5c2b82cdab64da7f5)

## Storage Files (REQUIRED)
LD_Checkedstorage (One line in the file only):
`0|12
`
The LD_Volcanostorage file was empty

**Comment by eleksploded** [comment]
Can you post your config file?

**Comment by WenXin20** [comment]
I realized that I forgot to remove the ore entry `mubble:vanadium_ore|0`. I had removed the Mubble mod but forgot I had added it's ore to the config. Could that be what is causing the crash?
[Config](https://gist.github.com/WenXin20/f56b50d2314b2ca6814cc42a9ca35290)

**Comment by eleksploded** [comment]
If that name doesn’t actually point to an actual block, then yes, that would cause the crash.

**Comment by kreezxil** [comment]
you should add code that quietly ignores bad entries the list but with a
loggable output when it does.

Like in console it should say "ignoring invalid block entry because it
doesn't exist modid:blockid"

**Comment by WenXin20** [comment]
I tried to create a WildNature world type again without the `mubble:vanadium_ore|0` entry, but I still get a crash, although it looks to be a bit different. 
[Crash Report](https://gist.github.com/WenXin20/1ddbd6f86c7a8830820584948a9e4a45)

**Comment by eleksploded** [comment]
Kreezxil, That is actually implemented in 5.6.7, but I'm still fixing some stuff up before releasing. I'll look over the new crash and see what I can do.
