### ISSUE TITLE
Make Volcanoes Respect Biome Block Pallet

### ISSUE THREAD

**Issue by AechtRob** [kreezxil/Lava-Dynamics#24]
LavaDynamics.... I noticed that volcanoes do not spawn at all if you set an ore distribution at less than 1 (eg. like 0.2). The volcanoes just don't appear, even when spawned in manually. What I was trying to do was set something like 80% of the volcano to generate as "ore", and then have most of that "ore" be defined as basalt, dirt and grass and only a VERY FEW other precious ores in it. That will give me a very naturalistic-looking volcano. For a large volcano that would mean setting the value for the precious ores at much less than 1. Maybe values like 0.01 or less. Can you enable the mod to process such low values please? At the moment for a large volcano there is no way to get a very low occurrence of an ore and replace a large amount of the stone with something else at the same time.

**Comment by kreezxil** [comment]
which minecraft version are you referring to? or what is the version of the
mod you have installed?

**Comment by AechtRob** [comment]
Apologies: lavadynamics-1.12.2-5.6.8.jar / MC 1.12.2 / Forge 14.23.5.2847

I would like this sort of thing to work, so that diamonds are still rare in a large grassy volcano, but setting any of the values under 1 causes the volcano not to spawn:

     I:chance <
         100
         **0.01**
      >
 
     I:oreChance=750
 
     S:ores <
         minecraft:grass|0
         minecraft:diamond_ore|0
      >

**Comment by eleksploded** [comment]
The problem is that the chance list only supports integers, not decimal values. Hence the "I:" in the front of the list.

**Comment by eleksploded** [comment]
Honestly, I'm surprised that didn't crash on startup.

**Comment by AechtRob** [comment]
OK - yes, that is the problem indeed. This is a suggestion to improve it so it can take decimals too though :) The maths which needs to be done by the code is the same maths.

**Comment by eleksploded** [comment]
True True. Although the way that the chance for ores work is that those numbers are the amount of chances that the specific ore has to spawn. Meaning decimal values don't really make sense.

**Comment by AechtRob** [comment]
OK how about this idea. All I am trying to do is get a more "natural-looking" volcano really, and this is a workaround.

When a volcano spawns, check what biome it is in. Each biome already has a "filler block" and a "top block" registered for it in eth game registries, which can be looked up in-mod. Instead of using minecraft:stone, use the biome's "filler block" when generating the volcano (or maybe allow the top 10% of the volcano to be standard stone?). That would then then make the volcano fit better into any biome and any any dimension nicely without much more effort.

This is just a suggestion to improve things, and to allow a more natural volcano while still keeping ore numbers low. So far my experiments with the mod have been mostly positive though, and minecraft is massively lacking this kind of thing working well.

**Comment by eleksploded** [comment]
Thanks! Ill look into that suggestion, seems like a pretty easy enhancement that would look really good.

**Comment by eleksploded** [comment]
Done!

**Comment by AechtRob** [comment]
Nice! :)

**Comment by AechtRob** [comment]
I guess for perfection maybe the top few layers (random) would be stone only, and never grass etc....?

**Comment by eleksploded** [comment]
I can do that

**Comment by AechtRob** [comment]
I'm not sure exactly what you'd need.. but some randomised factor of making the top stone may look good. Also, not sure what's possible but again, perhaps you can pick up the surface floral (etc) decorations and trees from the biome and add them on the volcanos, but only up to a certain height - would have to experiment to see what height looks best,. Maybe a percentage, maybe absolute.

Incidentally..... I have noticed that large volcano spawning does already sometimes generate surface biome decorations, even trees. But never on the "new" side of the volcano. The volcano spawns and the near-side of it, facing the player, takes the standard plain surface. But then as the player starts to move round the volcano and the chunks for the rest of the back of the volcano load in for the first time they seem to pick up the decorations/trees from the parent biome: which was nice, though I guess wasn't really under strict control? Sometimes for big volcanos they even reached the top if the top chunk didn't render in at the same time as the initial gen.

**Comment by eleksploded** [comment]
If you are using world gen, it is probably generating the biome decoration on the back side because those chunks are being decorated after the volcano has spawned.
