### ISSUE TITLE
Conflict with Lycanites mobs

### ISSUE THREAD

**Issue by AechtRob** [kreezxil/Lava-Dynamics#27]
MC 1.12.2. When Lycanites mobs (https://www.curseforge.com/minecraft/mc-mods/lycanites-mobs) is installed with Lavadynamics (https://www.curseforge.com/minecraft/mc-mods/lava-dynamics) all blocks next to flowing lava turn into terracotta, and breaking a block in that position turns it immediately into terracotta, replacing air if necessary. To replicate: install both mods and go into spectator mode and fly around to observe flowing lava.

(This breaks volcano spawns as well)

Reported to both mod-issues pages.

**Comment by eleksploded** [comment]
I possibly fixed it in 5.6.12, but its just a work-around right now. Leaving open until a true fix is available.

**Comment by AechtRob** [comment]
Just gotta say.... realising that you can smelt simply directly over flowing lava with this mod so easily is really rather cool. I hadn't explored that functionality til this bug!

**Comment by eleksploded** [comment]
Pretty sure this is a problem on Lycanites side. Closing
