### ISSUE TITLE
Volcanoes spawn on top of player spawnpoint

### ISSUE THREAD

**Issue by AechtRob** [kreezxil/Lava-Dynamics#28]
MC 1.12.2. Latest version of lavadynamics (lavadynamics-1.12.2-5.6.10). When volcanoes are set to generate during world-gen, and if they are large and you set the probability of generation high, one usually generates on top of the player spawn point, burying the player. I think what you need is to add a config option to allow owners to prevent a volcano a certain distance from the **worldspawn** point.

(The player spawns will be different distances from that position, depending on whether it's a multiplayer or single player setup, but owners can then decide how best to set the config.)

**Comment by eleksploded** [comment]
Can do!

**Comment by eleksploded** [comment]
Added in 5.6.11

**Comment by AechtRob** [comment]
You're a star. Thanks!
