### ISSUE TITLE
Volcanos not spawning

### ISSUE THREAD

**Issue by AechtRob** [kreezxil/Lava-Dynamics#29]
The latest versions of lavadynamics (lavadynamics-1.12.2-5.6.12), with the spawn-chunk protection in the config, doesn't seem to create volcanoes at all, if set to do during word-gen. I tried these settings (they seemed most likely to allow frequent obvious volcanoes!) but nothing appears anywhere:

I:distance=200
B:protectChunks=false
B:spawnChunks=true
I:spawnDistance=5
I:volcanoChance=100
I:volcanoHeightMax=101
I:volcanoHeightMin=50
B:worldGen=true

(When I set worldgen=false they do spawn fine).

**Comment by eleksploded** [comment]
Sorry that took so long, I basically just rewrote the world gen procedure. Sure be fixed now. (5.6.13)
