### ISSUE TITLE
Too Many Volcanos

### ISSUE THREAD

**Issue by ghost** [kreezxil/Lava-Dynamics#5]
![sss](https://user-images.githubusercontent.com/24831406/40423840-686ed03c-5e9c-11e8-92aa-71af36dd0f26.png)
how to prevent this? i mean how can i decrease the quantity of them?
is it normal, or a bug? cus it's my modpack.
if not a bug and it's normal, can you decrease it? xD

**Comment by kreezxil** [comment]
In **lavadynamics.cfg** find the following section. Bear in mind that volcanos erupt naturally over time, they are not worldgen items. 

These settings will drastically reduce volcano occurrences. If you set the y level to 5 or even 3, then only lava nearer to bedrock will be considered for volcanic eruption. Volcanos come from magma vents.

Revisiting an area gives every lava source block another chance at eruption. Even then if there is a ton of lava down below even at 10% chance the chance of a lot of volcanos is high. Example get 3 6 sized die. The chance of rolling 3 1's in extremely rare. Imagine there are 5 cups of water on the table. Each time you come near the table you roll all 3 dice for each of the 5 cups. If 3 1's appear, you drink that glass and refill it. Each time you come to the table. So drop **volcano chance** to a value lower than 10, like maybe 1 for you.

Another way to reduce the volcanos is to change **psuedoSurface** to value lower than 69. Change it to 25 for example and the base of the volcanos will start at 25 and only rise as high as **extraHt** under _**Plume Height**_.

```
"volcano settings" {
    # The max y value to consider for turning lava into a magma vent.
    # Default: 10
    I:maxYlevel=10

    # 0 to 100 chance that part of the nodule is formed to protect the ore being generated
    I:nodulePartChance=10

    # if true any tile entity will prevent a volcano from erupting in a chunk. Signs are tile entities btw. Setting this to false enables hardcore volcanoes. Meaning a play must neutralize lava pools below them to be truly safe.
    B:protection=true

    # The y level for the approximate level of your surface.
    # Default: 69
    I:psuedoSurface=69

    # Percent chance a volcano or magma vent will occur.
    # Default: 20
    I:volcanoChance=20

    # You can play with this value, but it's not for you.
    # Default: seriously it will ignore you
    B:volcanoGen=false
}
```
